### ISSUE TITLE
Relationship labels do not appear in generated Graphical Context Map

### ISSUE THREAD

**Issue by socadk** [ContextMapper/context-mapper-dsl#184]
They do make to the generated UML. Would be nice to also have them appear as labels in the GraphViz output.

**Comment by stefan-ka** [comment]
Will be fixed with next release (v5.10.x or higher).

A dialog now allows to control whether labels (name and implementation technology) shall be generated:

![image](https://user-images.githubusercontent.com/6763278/77823650-05872080-70fd-11ea-877d-0ef390c73ab4.png)

If selected (currently the default), the generator adds the two attributes as labels to the generated Context Maps. An example:

![image](https://user-images.githubusercontent.com/6763278/77823716-74fd1000-70fd-11ea-8c4d-a161cde5995c.png)
