### ISSUE TITLE
Add relationship type to puml even if optional label is present

### ISSUE THREAD

**Issue by socadk** [ContextMapper/context-mapper-dsl#186]
example: 
if a Partnership has a label "myLabel", the generated puml relation could be labelled "myLabel (Partnership)" (rationale: avoid information loss)

**Comment by stefan-ka** [comment]
Will be fixed with next release (v5.10.x or higher).

The following relationship...
```
RiskManagementContext [P]<->[P] PolicyManagementContext : myLabel
```
... produces this result now:
![image](https://user-images.githubusercontent.com/6763278/77820624-efb93180-70e3-11ea-8aa7-d8eddf2b14f4.png)

If the relationship has an implementation technology like this:
```
RiskManagementContext [P]<->[P] PolicyManagementContext : myLabel {
  implementationTechnology = "RabbitMQ"
}
```
it produces the following result:
![image](https://user-images.githubusercontent.com/6763278/77820676-3ad34480-70e4-11ea-9a14-4424f9376e8c.png)
