### ISSUE TITLE
MacOs plugin

### ISSUE THREAD

**Issue by renatocosta** [ContextMapper/context-mapper-dsl#199]
Hello.
I am trying generate the graphic but I can't as bellow:

Configuration: MacOs Catalina

dot -V
dot - graphviz version 2.42.3 (20191010.1750)

Eclipse 2020-03 (4.15.0)

Error: Graphviz has not been found on your system. Ensure it is installed and the binaries are part of your PATH environment variable

My path environment: /usr/local/Cellar/graphviz/2.42.3/bin/dot:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Can you help me?

<img width="1680" alt="Screen Shot 2020-04-12 at 19 16 32" src="https://user-images.githubusercontent.com/638176/79081379-37020d80-7cf3-11ea-8bd3-3ae4e23e2f58.png">
<img width="6" alt="Screen Shot 2020-04-12 at 19 16 55" src="https://user-images.githubusercontent.com/638176/79081382-3bc6c180-7cf3-11ea-8c87-d656fc64e944.png">
<img width="1680" alt="Screen Shot 2020-04-12 at 19 16 53" src="https://user-images.githubusercontent.com/638176/79081390-4f722800-7cf3-11ea-87e2-4ed04f25c59e.png">

**Comment by stefan-ka** [comment]
Hi @renatocosta 

Thanks for reporting this. Seems like there is a problem with the Eclipse plugin on MacOS. I'm however not yet sure what the problem is here.

Can you check for me if it works in a standalone Java program?
You can checkout the project here... https://github.com/ContextMapper/context-mapper-standalone-example
... and then try to run the following Java program: https://github.com/ContextMapper/context-mapper-standalone-example/blob/master/src/main/java/org/contextmapper/standalone/example/ContextMapGeneratorExample.java
The `main` program should generate a Context Map graphic into the `src-gen`. 

Would be good to know if this doesn't work as well or if it is a problem of the Eclipse plugin.

Thanks!

**Comment by stefan-ka** [comment]
Hi @renatocosta,

We identified the problem... Thanks to @misto, who used the plugin on MacOS as well.
He was able to fix this on his machine with the solution described here:
https://stackoverflow.com/questions/34022487/add-usr-local-bin-to-path-got-from-system-getenvpath-in-java-run-on-mac-os

Can you check if this works for you as well?

Thanks and best regards,
Stefan

**Comment by renatocosta** [comment]
Hi @stefan-ka,

Thank you for your attention.
Unfortunately, I can't solve that yet. I just followed all of tips above as well as I changed the environment variables and then no works.

Mac Os Catalina.
`echo $PATH` 
`/usr/local/opt/graphviz/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Could you post your $PATH environment?

Thank you again

**Comment by stefan-ka** [comment]
@renatocosta, you can also not get it running with the Java program a mentioned above (standalone)?

**Comment by stefan-ka** [comment]
@renatocosta, could you check if the solutions here https://stackoverflow.com/questions/34022487/add-usr-local-bin-to-path-got-from-system-getenvpath-in-java-run-on-mac-os work if you start Eclipse from the commandline? (as a workaround)

**Comment by renatocosta** [comment]
> @renatocosta, you can also not get it running with the Java program a mentioned above (standalone)?

Not yet.

**Comment by renatocosta** [comment]
> workaround

**Comment by renatocosta** [comment]
> @renatocosta, could you check if the solutions here https://stackoverflow.com/questions/34022487/add-usr-local-bin-to-path-got-from-system-getenvpath-in-java-run-on-mac-os work if you start Eclipse from the commandline? (as a workaround)

I just can do that.
Thank you for all your support.
