### ISSUE TITLE
lsp build instructions missing

### ISSUE THREAD

**Issue by JuergenMutschall** [ContextMapper/context-mapper-dsl#306]
Hi,

I was able to build and run the eclipse and the vscode integration.
The vsix downloads and runs a context-mapper-lsp-6.5.0.jar. 
I would like to build the language server in eclipse, based on context-mapper-dsl and the other plugins. 
Where can I find the build instructions/scripts?

Regards,

Juergen

**Comment by stefan-ka** [comment]
Hi @JuergenMutschall 

Sorry for not answering this one so far... Must have missed the notification.

Is this still an issue for you?
I'm not 100% sure what you mean exactly. You can import and build the whole project as a Maven project into Eclipse. The language server is contained by the `org.contextmapper.dsl.ide` sub-project. In the `org.contextmapper.dsl.ide.tests` there are also many unit and integration tests for the language server. The vsix however can only be build via the Gradle build (I know it's not the most elegant solution to have two build tools; I prefer Gradle where possible, for example for the language server, but we cannot avoid Maven because of the Eclipse plugin).

Best regards,
Stefan

**Comment by stefan-ka** [comment]
Hi @JuergenMutschall 
As you haven't answered anymore I assume this is no longer an issue. I will close the issue. If you still have problems feel free to re-open or create other issues.
Best regards, Stefan
